### ISSUE TITLE
Device model documentation issue

### ISSUE THREAD

**Issue by naweliiot** [relayr/DeveloperDocumentation#12]
First of all Thank you for describing the thing in simple words

here is couple of advice

1)You can provide a link to API For HTTP & MQTT

2)Describe the "Meaning" for Reading section in better way.

3)Why Website is (if applicable) because I saw it Mandatory field. If its Mandatory then we have to provide url.

I think we can talk to device model team and ask them to not make it mandatory.

4) SHOW JSON button should be Red Mar. Its very nice feature in device model.

5)properties part can be improved.(its scary now)

**Comment by lemkeb** [comment]
Will talk to frontend team about required website field
