### ISSUE TITLE
Avoid blank statements

### ISSUE THREAD

**Issue by perusio** [relayr/DeveloperDocumentation#15]
Instead of:

<blockquote>
Device models are stored in the relayr cloud as JSON schemas that define the structure and functionality of any device using that model.
</blockquote>

write:

A device model is stored in the relayr cloud as a JSON object implementing a a device schema that defines the structure and functionality of any device using that model. As explained above. For example here's the device model for the a **temperature** and **humidity** sensor from the [Wunderbar](https://relayr.io/wunderbar).

**Comment by lemkeb** [comment]
Clarified this statement
