### ISSUE TITLE
Device models guide issues

### ISSUE THREAD

**Issue by deeplook** [relayr/DeveloperDocumentation#17]
https://github.com/relayr/DeveloperDocumentation/blob/recipes/device-models-guide.mdown

- extension .mdown??
- "A reading is a value **of a measurement** that is sent by a connected device."
- when speaking of paths it doesn't say they can be structured
- missing a simple way to express choices like (2, 4, 6), but that's a backend limit  
- creating a device model, 5. Array is not clear, I imagine it refers to a value whenever it is an array, but this should be made more explicit.

**Comment by lemkeb** [comment]
Incorporated revisions into e74f8b1
