### ISSUE TITLE
Token creation issues

### ISSUE THREAD

**Issue by deeplook** [relayr/DeveloperDocumentation#19]
https://github.com/relayr/DeveloperDocumentation/blob/recipes/token-creation.md

- pointing to https://tools.ietf.org/html/rfc6749 for getting familiar with OAuth is kind of sarcastic. This should be something easier to digest.
- under "Register your app" (3) "New API key" is kind of questionable, since one creates an entire "app" as the pop-up popping up next says... the Dashboard UI isn't stellar here, so maybe the docs have to be... sigh.
- (5) Why the "Deprecated" in "Client ID: Deprecated"? in the image "CReate New App (3/3)"?

**Comment by lemkeb** [comment]
Made revisions in f7ae08e
