### ISSUE TITLE
Device groups: Removing a device

### ISSUE THREAD

**Issue by klemenl** [relayr/DeveloperDocumentation#21]
I couldn't figure out how to remove a device from a group. Looks like Dashboard is not listing the devices already included in the group; so not really a docs issue.

**Comment by lemkeb** [comment]
This is a bug; https://relayr.tpondemand.com/RestUI/Board.aspx?acid=5D6AC326B4D272C23E446C28586BAF51#page=board/5520273160654391762&appConfig=eyJhY2lkIjoiOEU5ODNBQ0MyMEU1NENCRTFEQ0UyM0QxMjcxNTFEMTcifQ==
