### ISSUE TITLE
Recipes: General (very minor things)

### ISSUE THREAD

**Issue by klemenl** [relayr/DeveloperDocumentation#22]
**Device Model:** Using a different term than 'sensor module' might be considered (embedded system, node, mote), since this is the first thing new users would read after creating an account.

https://www.google.de/search?q=sensor+module&espv=2&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjx5ZzthZvMAhVMuBQKHfa9ApoQ_AUIBygB&biw=1280&bih=678

Path could be added to first commands JSON example (just to have a full example), maybe 'soundTheAlarm' renamed.

**Devices:** Moving the description of 'adding a device', above 'viewing a device' might be useful for first time user of Dashboard, but then again less useful for more experienced users.

**Comment by lemkeb** [comment]
Incorporated the feedback into e74f8b1. Agree with moving the "adding a device" section up because the intended audience is first-time users.
