### ISSUE TITLE
Issue while adding detail of device mode

### ISSUE THREAD

**Issue by naweliiot** [relayr/DeveloperDocumentation#28]
Here are couple of issue i found. 
<img width="753" alt="screenshot at apr 20 11-58-22" src="https://cloud.githubusercontent.com/assets/16141572/14670983/ce1a3e8c-06ef-11e6-9c59-866eea4136ea.png">
<img width="422" alt="screenshot at apr 20 11-55-54" src="https://cloud.githubusercontent.com/assets/16141572/14670984/ce407e9e-06ef-11e6-84a2-1f07a04fca28.png">

1)why the website is mandatory. if its mandatory it should b applicable.

2)Seriously speaking I still don't understand the value of meaning in the Reading section. is it "key":""value" pair in json

**Comment by lemkeb** [comment]
Clarified in 408ed16
