### ISSUE TITLE
For the token creation document

### ISSUE THREAD

**Issue by perusio** [relayr/DeveloperDocumentation#30]
1. Provide a one paragraph context for what an app is in the relayr cloud. There are apps, devices, transmitters...check with the frontend/backend team.
 2. Useful to include cURL requests with the responses for each API call.

**Comment by deeplook** [comment]
A glossary is what I'd like to see... cURLs, yes, code rules!

**Comment by lemkeb** [comment]
Addressed in 936c4a6. Glossary to follow
