### ISSUE TITLE
Adding your first device

### ISSUE THREAD

**Issue by perusio** [relayr/DeveloperDocumentation#47]
1. What is a physical device? One short sentence.
 2. What is a virtual device? One short sentence.
 3. Point to a later elaboration on what a device is. Here is curt phrases.
 4. One short sentence on MQTT. This should link to architectural overview document.
 5. Link to Python programming language. Hey this is an doc with *hyperlinks*.

**Comment by lemkeb** [comment]
Addressed in 1f7b24c6a96a08b068fd2e542d73988201c262b5
