### ISSUE TITLE
Device data overview

### ISSUE THREAD

**Issue by perusio** [relayr/DeveloperDocumentation#48]
1. Should read: _how you can manipulate the data being sent by your virtual device_.
 2. Distinguish between *basic* or *simple* value types (string, number, boolean) vs *complex* value types (objects).
 3. Please explain properly what is an *integer* and a *number*. Numbers include integers, basically is either a float or an integer. In math terms a number is a *real number*, although computers cannot hold irrational numbers, just for FYI.
 4. Please use *json* for highlighting.
 5. Link to WiFi and RSSI.

**Comment by lemkeb** [comment]
Addressed in bfdd8b3b54d15fcef221f16ca6a89162e2574940
