### ISSUE TITLE
Get device data

### ISSUE THREAD

**Issue by perusio** [relayr/DeveloperDocumentation#49]
1. Highlighting properly: *shell*, *SQL*.
 2. Links to Grafana and InfluxDB sites.
 3. Explain in one sentence what Grafana and Influx are. Links for further explanantion.
 4. Is not _wherever InfluxDB is running on your machine, if different_, is replace with the port where InfluxDB is running.
 5. Two sentence explanation of InfluxDB query language, explain SQL inspiration: link.
 6. Provide links for further exploring Grafana and InfluxDB.

**Comment by lemkeb** [comment]
Addressed in 3f011c55e090f7424f3d81e63aaef2c3a56272ae
