### ISSUE TITLE
Device models

### ISSUE THREAD

**Issue by perusio** [relayr/DeveloperDocumentation#50]
1. Remove Wunderbar example. 
 2. This seems to be out of place and pace. In the sense that is confusing now explaining how the virtual device work after having talk about it at length before.
 3. Remove references to specific devices firmware: is only for Arduino and not very relevant IMHO.
 4. This > Suppose you had a group of embedded systems that measured temperature and humidity at a customizable time 
is convoluted and wrong. We talk about *sensor nodes* and *actuator nodes*. Usually just the first since that is assumed to also have actuators if possible and/or needed.
6. Typo in writing link with anchor metadata showing.

**Comment by lemkeb** [comment]
Addressed in c2f83d7552981c7cfabcceaeeacd16dc7272eae1
